version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "celery -A task.celery_app worker -l info"
        restart: on-failure
        env_file:
            - .env
        volumes:
            - ./src:/app
        depends_on:
            - redis
        networks:
            - proxynet

    redis:
        image: 'redis:5-alpine'
        ports:
        - '6378:6379'
networks:
  proxynet:
    name: qcoom_network
